version: "3"

# TODO(before release): add the Nest.js application to the docker-compose.yml
services:
  db:
    image: postgres:15
    restart: always
    # TODO(before release): don't store the password here
    environment:
      POSTGRES_USER: postgres
      # TODO(before release): add prod db here as well
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
